class TableClass {
  final String name;
  final int point;
  final String form;
  final int win;
  final int draw;
  final int lose;
  final int place;

  TableClass({
    required this.name,
    required this.point,
    required this.form,
    required this.win,
    required this.draw,
    required this.lose,
    required this.place,
  });
}

final List<TableClass> getTable = [
  TableClass(
    name: 'Manchester City',
    point: 86,
    form: 'WLWLW',
    win: 27,
    draw: 5,
    lose: 6,
    place: 1,
  ),
  TableClass(
    name: 'Manchester United',
    point: 74,
    form: 'WDLLW',
    win: 21,
    draw: 11,
    lose: 6,
    place: 2,
  ),
  TableClass(
    name: 'Liverpool',
    point: 69,
    form: 'WWWWW',
    win: 20,
    draw: 9,
    lose: 9,
    place: 3,
  ),
  TableClass(
    name: 'Chelsea',
    point: 67,
    form: 'LWLWW',
    win: 19,
    draw: 10,
    lose: 9,
    place: 4,
  ),
  TableClass(
    name: 'Leicester',
    point: 66,
    form: 'LLWLD',
    win: 20,
    draw: 6,
    lose: 12,
    place: 5,
  ),
  TableClass(
    name: 'West Ham',
    point: 65,
    form: 'WWDLW',
    win: 19,
    draw: 8,
    lose: 11,
    place: 6,
  ),
  TableClass(
    name: 'Tottenham',
    point: 62,
    form: 'WLWLW',
    win: 18,
    draw: 8,
    lose: 12,
    place: 7,
  ),
  TableClass(
    name: 'Arsenal',
    point: 61,
    form: 'WWWWW',
    win: 18,
    draw: 7,
    lose: 13,
    place: 8,
  ),
  TableClass(
    name: 'Leeds',
    point: 59,
    form: 'WWWWL',
    win: 18,
    draw: 5,
    lose: 15,
    place: 9,
  ),
  TableClass(
    name: 'Everton',
    point: 59,
    form: 'LWLDW',
    win: 17,
    draw: 8,
    lose: 13,
    place: 10,
  ),
  TableClass(
    name: 'Aston Villa',
    point: 55,
    form: 'WWLDL',
    win: 16,
    draw: 7,
    lose: 15,
    place: 11,
  ),
  TableClass(
    name: 'Newcastle',
    point: 45,
    form: 'WWLWL',
    win: 12,
    draw: 9,
    lose: 17,
    place: 12,
  ),
  TableClass(
    name: 'Wolves',
    point: 45,
    form: 'LLLWD',
    win: 12,
    draw: 9,
    lose: 17,
    place: 13,
  ),
  TableClass(
    name: 'Crystal Palace',
    point: 44,
    form: 'LLWLW',
    win: 12,
    draw: 8,
    lose: 18,
    place: 14,
  ),
  TableClass(
    name: 'Southampton',
    point: 43,
    form: 'LLWWL',
    win: 12,
    draw: 7,
    lose: 19,
    place: 15,
  ),
  TableClass(
    name: 'Brighton',
    point: 41,
    form: 'LWDLW',
    win: 9,
    draw: 14,
    lose: 15,
    place: 16,
  ),
  TableClass(
    name: 'Burnley',
    point: 39,
    form: 'LLLWL',
    win: 10,
    draw: 9,
    lose: 19,
    place: 17,
  ),
  TableClass(
    name: 'Fulham',
    point: 28,
    form: 'LDLLL',
    win: 5,
    draw: 13,
    lose: 20,
    place: 18,
  ),
  TableClass(
    name: 'West Brom',
    point: 26,
    form: 'LLLLD',
    win: 5,
    draw: 11,
    lose: 22,
    place: 19,
  ),
  TableClass(
    name: 'Sheffield Utd',
    point: 23,
    form: 'WLWLL',
    win: 7,
    draw: 2,
    lose: 29,
    place: 20,
  )
];
