// ignore_for_file: void_checks

class StatisticsClass {
  final String name;
  final String nation;
  final String club;
  final String pictureUrl;
  final int total;

  StatisticsClass({
    required this.name,
    required this.nation,
    required this.club,
    required this.pictureUrl,
    required this.total,
  });
}

final List<StatisticsClass> getTopScore = [
  StatisticsClass(
    name: 'H. Kane',
    nation: 'England',
    club: 'Tottenham',
    pictureUrl: 'https://media.api-sports.io/football/players/184.png',
    total: 23,
  ),
  StatisticsClass(
    name: 'Mohamed Salah',
    nation: 'Egypt',
    club: 'Liverpool',
    pictureUrl: 'https://media.api-sports.io/football/players/306.png',
    total: 22,
  ),
  StatisticsClass(
    name: 'Bruno Fernandes',
    nation: 'Portugal',
    club: 'Manchester United',
    pictureUrl: 'https://media.api-sports.io/football/players/1485.png',
    total: 18,
  ),
  StatisticsClass(
    name: 'Son Heung-Min',
    nation: 'Korea Republic',
    club: 'Tottenham',
    pictureUrl: 'https://media.api-sports.io/football/players/186.png',
    total: 17,
  ),
  StatisticsClass(
    name: 'P. Bamford',
    nation: 'England',
    club: 'Leeds',
    pictureUrl: 'https://media.api-sports.io/football/players/19134.png',
    total: 17,
  ),
  StatisticsClass(
    name: 'D. Calvert-Lewin',
    nation: 'England',
    club: 'Everton',
    pictureUrl: 'https://media.api-sports.io/football/players/18766.png',
    total: 16,
  ),
  StatisticsClass(
    name: 'J. Vardy',
    nation: 'England',
    club: 'Leicester',
    pictureUrl: 'https://media.api-sports.io/football/players/18788.png',
    total: 15,
  ),
  StatisticsClass(
    name: 'O. Watkins',
    nation: 'England',
    club: 'Aston Villa',
    pictureUrl: 'https://media.api-sports.io/football/players/19366.png',
    total: 14,
  ),
  StatisticsClass(
    name: 'İ. Gündoğan',
    nation: 'Germany',
    club: 'Manchester City',
    pictureUrl: 'https://media.api-sports.io/football/players/633.png',
    total: 13,
  ),
  StatisticsClass(
    name: 'A. Lacazette',
    nation: 'France',
    club: 'Arsenal',
    pictureUrl: 'https://media.api-sports.io/football/players/1467.png',
    total: 13,
  ),
  StatisticsClass(
    name: 'K. Iheanacho',
    nation: 'Nigeria',
    club: 'Leicester',
    pictureUrl: 'https://media.api-sports.io/football/players/2778.png',
    total: 12,
  ),
  StatisticsClass(
    name: 'D. Ings',
    nation: 'England',
    club: 'Southampton',
    pictureUrl: 'https://media.api-sports.io/football/players/18955.png',
    total: 12,
  ),
  StatisticsClass(
    name: 'C. Wood',
    nation: 'New Zealand',
    club: 'Burnley',
    pictureUrl: 'https://media.api-sports.io/football/players/18931.png',
    total: 12,
  ),
  StatisticsClass(
    name: 'C. Wilson',
    nation: 'England',
    club: 'Newcastle',
    pictureUrl: 'https://media.api-sports.io/football/players/2939.png',
    total: 12,
  ),
  StatisticsClass(
    name: 'M. Rashford',
    nation: 'England',
    club: 'Manchester United',
    pictureUrl: 'https://media.api-sports.io/football/players/909.png',
    total: 11,
  ),
  StatisticsClass(
    name: 'S. Mané',
    nation: 'Senegal',
    club: 'Liverpool',
    pictureUrl: 'https://media.api-sports.io/football/players/304.png',
    total: 11,
  ),
  StatisticsClass(
    name: 'G. Bale',
    nation: 'Wales',
    club: 'Tottenham',
    pictureUrl: 'https://media.api-sports.io/football/players/758.png',
    total: 11,
  ),
  StatisticsClass(
    name: 'W. Zaha',
    nation: "Côte d'Ivoire",
    club: 'Crystal Palace',
    pictureUrl: 'https://media.api-sports.io/football/players/3247.png',
    total: 11,
  ),
  StatisticsClass(
    name: 'Matheus Pereira',
    nation: 'Brazil',
    club: 'West Brom',
    pictureUrl: 'https://media.api-sports.io/football/players/25618.png',
    total: 11,
  ),
  StatisticsClass(
    name: 'R. Sterling',
    nation: 'England',
    club: 'Manchester City',
    pictureUrl: 'https://media.api-sports.io/football/players/645.png',
    total: 10,
  ),
];

final List<StatisticsClass> getTopAssists = [
  StatisticsClass(
    name: 'H. Kane',
    nation: 'England',
    club: 'Tottenham',
    pictureUrl: 'https://media.api-sports.io/football/players/184.png',
    total: 14,
  ),
  StatisticsClass(
    name: 'Bruno Fernandes',
    nation: 'Portugal',
    club: 'Manchester United',
    pictureUrl: 'https://media.api-sports.io/football/players/1485.png',
    total: 12,
  ),
  StatisticsClass(
    name: 'K. De Bruyne',
    nation: 'Belgium',
    club: 'Manchester City',
    pictureUrl: 'https://media.api-sports.io/football/players/629.png',
    total: 12,
  ),
  StatisticsClass(
    name: 'Son Heung-Min',
    nation: 'Korea Republic',
    club: 'Tottenham',
    pictureUrl: 'https://media.api-sports.io/football/players/186.png',
    total: 10,
  ),
  StatisticsClass(
    name: 'J. Grealish',
    nation: 'England',
    club: 'Aston Villa',
    pictureUrl: 'https://media.api-sports.io/football/players/19187.png',
    total: 10,
  ),
  StatisticsClass(
    name: 'J. Vardy',
    nation: 'England',
    club: 'Leicester',
    pictureUrl: 'https://media.api-sports.io/football/players/18788.png',
    total: 9,
  ),
  StatisticsClass(
    name: 'M. Rashford',
    nation: 'England',
    club: 'Manchester United',
    pictureUrl: 'https://media.api-sports.io/football/players/909.png',
    total: 9,
  ),
  StatisticsClass(
    name: 'Raphinha',
    nation: 'Brazil',
    club: 'Leeds',
    pictureUrl: 'https://media.api-sports.io/football/players/1496.png',
    total: 9,
  ),
  StatisticsClass(
    name: 'J. Harrison',
    nation: 'England',
    club: 'Leeds',
    pictureUrl: 'https://media.api-sports.io/football/players/19128.png',
    total: 8,
  ),
  StatisticsClass(
    name: 'T. Werner',
    nation: 'Germany',
    club: 'Chelsea',
    pictureUrl: 'https://media.api-sports.io/football/players/1166.png',
    total: 8,
  ),
  StatisticsClass(
    name: 'P. Groß',
    nation: 'Germany',
    club: 'Brighton',
    pictureUrl: 'https://media.api-sports.io/football/players/18970.png',
    total: 8,
  ),
  StatisticsClass(
    name: 'A. Cresswell',
    nation: 'England',
    club: 'West Ham',
    pictureUrl: 'https://media.api-sports.io/football/players/18813.png',
    total: 8,
  ),
  StatisticsClass(
    name: 'P. Bamford',
    nation: 'England',
    club: 'Leeds',
    pictureUrl: 'https://media.api-sports.io/football/players/19134.png',
    total: 7,
  ),
  StatisticsClass(
    name: 'S. Mané',
    nation: 'Senegal',
    club: 'Liverpool',
    pictureUrl: 'https://media.api-sports.io/football/players/304.png',
    total: 7,
  ),
  StatisticsClass(
    name: 'R. Sterling',
    nation: 'England',
    club: 'Manchester City',
    pictureUrl: 'https://media.api-sports.io/football/players/645.png',
    total: 7,
  ),
  StatisticsClass(
    name: 'Roberto Firmino',
    nation: 'Brazil',
    club: 'Liverpool',
    pictureUrl: 'https://media.api-sports.io/football/players/302.png',
    total: 7,
  ),
  StatisticsClass(
    name: 'J. Ward-Prowse',
    nation: 'England',
    club: 'Southampton',
    pictureUrl: 'https://media.api-sports.io/football/players/2938.png',
    total: 7,
  ),
  StatisticsClass(
    name: 'T. Alexander-Arnold',
    nation: 'England',
    club: 'Liverpool',
    pictureUrl: 'https://media.api-sports.io/football/players/283.png',
    total: 7,
  ),
  StatisticsClass(
    name: 'A. Robertson',
    nation: 'Scotland',
    club: 'Liverpool',
    pictureUrl: 'https://media.api-sports.io/football/players/289.png',
    total: 7,
  ),
  StatisticsClass(
    name: 'V. Coufal',
    nation: 'Czech Republic',
    club: 'West Ham',
    pictureUrl: 'https://media.api-sports.io/football/players/1231.png',
    total: 7,
  ),
];

final List<StatisticsClass> getTopRedCard = [
  StatisticsClass(
    name: 'L. Dunk',
    nation: 'England',
    club: 'Brighton',
    pictureUrl: 'https://media.api-sports.io/football/players/18963.png',
    total: 2,
  ),
  StatisticsClass(
    name: 'Y. Bissouma',
    nation: 'Mali',
    club: 'Brighton',
    pictureUrl: 'https://media.api-sports.io/football/players/18968.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'L. Milivojević',
    nation: 'Serbia',
    club: 'Crystal Palace',
    pictureUrl: 'https://media.api-sports.io/football/players/18852.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'J. Lundstram',
    nation: 'England',
    club: 'Sheffield Utd',
    pictureUrl: 'https://media.api-sports.io/football/players/19104.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'T. Souček',
    nation: 'Czech Republic',
    club: 'West Ham',
    pictureUrl: 'https://media.api-sports.io/football/players/1243.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'G. Xhaka',
    nation: 'Switzerland',
    club: 'Arsenal',
    pictureUrl: 'https://media.api-sports.io/football/players/1464.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'J. Egan',
    nation: 'Republic of Ireland',
    club: 'Sheffield Utd',
    pictureUrl: 'https://media.api-sports.io/football/players/19093.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'J. Andersen',
    nation: 'Denmark',
    club: 'Fulham',
    pictureUrl: 'https://media.api-sports.io/football/players/2729.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'J. Bednarek',
    nation: 'Poland',
    club: 'Southampton',
    pictureUrl: 'https://media.api-sports.io/football/players/2999.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'João Cancelo',
    nation: 'Portugal',
    club: 'Manchester City',
    pictureUrl: 'https://media.api-sports.io/football/players/855.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'Azpilicueta',
    nation: 'Spain',
    club: 'Chelsea',
    pictureUrl: 'https://media.api-sports.io/football/players/2280.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'Richarlison',
    nation: 'Brazil',
    club: 'Everton',
    pictureUrl: 'https://media.api-sports.io/football/players/2413.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'A. Robinson',
    nation: 'USA',
    club: 'Fulham',
    pictureUrl: 'https://media.api-sports.io/football/players/19549.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'L. Cooper',
    nation: 'Scotland',
    club: 'Leeds',
    pictureUrl: 'https://media.api-sports.io/football/players/19118.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'F. Schär',
    nation: 'Switzerland',
    club: 'Newcastle',
    pictureUrl: 'https://media.api-sports.io/football/players/2806.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'S. Ajayi',
    nation: 'Nigeria',
    club: 'West Brom',
    pictureUrl: 'https://media.api-sports.io/football/players/2769.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'J. Vestergaard',
    nation: 'Denmark',
    club: 'Southampton',
    pictureUrl: 'https://media.api-sports.io/football/players/18943.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'Matheus Pereira',
    nation: 'Brazil',
    club: 'West Brom',
    pictureUrl: 'https://media.api-sports.io/football/players/25618.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'L. Digne',
    nation: 'France',
    club: 'Everton',
    pictureUrl: 'https://media.api-sports.io/football/players/2724.png',
    total: 1,
  ),
  StatisticsClass(
    name: 'J. Livermore',
    nation: 'England',
    club: 'West Brom',
    pictureUrl: 'https://media.api-sports.io/football/players/19160.png',
    total: 1,
  ),
];

final List<StatisticsClass> getTopYellowCard = [
  StatisticsClass(
    name: 'J.  McGinn',
    nation: 'Scotland',
    club: 'Aston Villa',
    pictureUrl: 'https://media.api-sports.io/football/players/19191.png',
    total: 12,
  ),
  StatisticsClass(
    name: 'H. Maguire',
    nation: 'England',
    club: 'Manchester United',
    pictureUrl: 'https://media.api-sports.io/football/players/2935.png',
    total: 11,
  ),
  StatisticsClass(
    name: 'C. Gallagher',
    nation: 'England',
    club: 'West Brom',
    pictureUrl: 'https://media.api-sports.io/football/players/67972.png',
    total: 11,
  ),
  StatisticsClass(
    name: 'K. Phillips',
    nation: 'England',
    club: 'Leeds',
    pictureUrl: 'https://media.api-sports.io/football/players/19130.png',
    total: 10,
  ),
  StatisticsClass(
    name: 'Douglas Luiz',
    nation: 'Brazil',
    club: 'Aston Villa',
    pictureUrl: 'https://media.api-sports.io/football/players/47522.png',
    total: 9,
  ),
  StatisticsClass(
    name: 'P. Højbjerg',
    nation: 'Denmark',
    club: 'Tottenham',
    pictureUrl: 'https://media.api-sports.io/football/players/2735.png',
    total: 9,
  ),
  StatisticsClass(
    name: 'M. Holgate',
    nation: 'England',
    club: 'Everton',
    pictureUrl: 'https://media.api-sports.io/football/players/19150.png',
    total: 9,
  ),
  StatisticsClass(
    name: 'Y. Bissouma',
    nation: 'Mali',
    club: 'Brighton',
    pictureUrl: 'https://media.api-sports.io/football/players/18968.png',
    total: 8,
  ),
  StatisticsClass(
    name: 'L. Milivojević',
    nation: 'Serbia',
    club: 'Crystal Palace',
    pictureUrl: 'https://media.api-sports.io/football/players/18852.png',
    total: 8,
  ),
  StatisticsClass(
    name: 'J. Lundstram',
    nation: 'England',
    club: 'Sheffield Utd',
    pictureUrl: 'https://media.api-sports.io/football/players/19104.png',
    total: 8,
  ),
  StatisticsClass(
    name: 'Rúben Neves',
    nation: 'Portugal',
    club: 'Wolves',
    pictureUrl: 'https://media.api-sports.io/football/players/2676.png',
    total: 8,
  ),
  StatisticsClass(
    name: 'L. Shaw',
    nation: 'England',
    club: 'Manchester United',
    pictureUrl: 'https://media.api-sports.io/football/players/891.png',
    total: 8,
  ),
  StatisticsClass(
    name: 'Bellerín',
    nation: 'Spain',
    club: 'Arsenal',
    pictureUrl: 'https://media.api-sports.io/football/players/1439.png',
    total: 8,
  ),
  StatisticsClass(
    name: 'I. Hayden',
    nation: 'England',
    club: 'Newcastle',
    pictureUrl: 'https://media.api-sports.io/football/players/18899.png',
    total: 8,
  ),
  StatisticsClass(
    name: 'M. Cash',
    nation: 'England',
    club: 'Aston Villa',
    pictureUrl: 'https://media.api-sports.io/football/players/19298.png',
    total: 7,
  ),
  StatisticsClass(
    name: 'T. Souček',
    nation: 'Czech Republic',
    club: 'West Ham',
    pictureUrl: 'https://media.api-sports.io/football/players/1243.png',
    total: 7,
  ),
  StatisticsClass(
    name: 'G. Xhaka',
    nation: 'Switzerland',
    club: 'Arsenal',
    pictureUrl: 'https://media.api-sports.io/football/players/1464.png',
    total: 7,
  ),
  StatisticsClass(
    name: 'J. Egan',
    nation: 'Republic of Ireland',
    club: 'Sheffield Utd',
    pictureUrl: 'https://media.api-sports.io/football/players/19093.png',
    total: 7,
  ),
  StatisticsClass(
    name: 'J. Andersen',
    nation: 'Denmark',
    club: 'Fulham',
    pictureUrl: 'https://media.api-sports.io/football/players/2729.png',
    total: 7,
  ),
  StatisticsClass(
    name: 'L. Ayling',
    nation: 'England',
    club: 'Leeds',
    pictureUrl: 'https://media.api-sports.io/football/players/19116.png',
    total: 7,
  )
];
